language: php

sudo: false

php:
  - 5.6
  - 7.3
  - 7.4snapshot

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 5.6
      env: PREFER_LOWEST=1

    - php: 7.3
      env: PHPCS=1 DEFAULT=0

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-source --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction ; fi

  - if [[ $PHPCS != 1 ]]; then composer require --dev phpunit/phpunit:"^5.7.14|^6.0"; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi

  - if [[ $PHPCS == 1 ]]; then composer cs-check; fi

notifications:
  email: false
